#pragma once
#include <Windows.h>
#include <iostream>
#include <thread>
#include <chrono>
#include <queue>
#define GLFW_INCLUDE_NONE
#define GLAD_GL_IMPLEMENTATION
#include <glad/gl.h>
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"
#include <GLFW/glfw3.h>
#define GLFW_EXPOSE_NATIVE_WIN32    
#include <GLFW/glfw3native.h>
#include <sqlite_orm/sqlite_orm.h>
